const BOOKING_STATUS = {
    DRAFT: "DRAFT",
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    RESCHEDULE_PROPOSED: "RESCHEDULE_PROPOSED",
    REJECTED: "REJECTED",
    CANCELLED_BY_USER: "CANCELLED_BY_USER",
    CANCELLED_BY_WORKSHOP: "CANCELLED_BY_WORKSHOP",
    EXPIRED: "EXPIRED",
    CHECKED_IN: "CHECKED_IN",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
    NO_SHOW: "NO_SHOW",
    DISPUTED: "DISPUTED"
};

const BOOKING_MODE = {
    INSTANT: "INSTANT",
    REQUEST: "REQUEST"
};

const allowedTransitions = {
    DRAFT: [BOOKING_STATUS.PENDING, BOOKING_STATUS.CONFIRMED, BOOKING_STATUS.CANCELLED_BY_USER],
    PENDING: [
        BOOKING_STATUS.CONFIRMED,
        BOOKING_STATUS.REJECTED,
        BOOKING_STATUS.RESCHEDULE_PROPOSED,
        BOOKING_STATUS.EXPIRED,
        BOOKING_STATUS.CANCELLED_BY_USER,
        BOOKING_STATUS.CANCELLED_BY_WORKSHOP
    ],
    RESCHEDULE_PROPOSED: [
        BOOKING_STATUS.CONFIRMED,
        BOOKING_STATUS.REJECTED,
        BOOKING_STATUS.CANCELLED_BY_USER,
        BOOKING_STATUS.EXPIRED
    ],
    CONFIRMED: [
        BOOKING_STATUS.IN_PROGRESS,
        BOOKING_STATUS.CANCELLED_BY_USER,
        BOOKING_STATUS.CANCELLED_BY_WORKSHOP,
        BOOKING_STATUS.NO_SHOW,
        BOOKING_STATUS.RESCHEDULE_PROPOSED
    ],
    CHECKED_IN: [BOOKING_STATUS.IN_PROGRESS, BOOKING_STATUS.CANCELLED_BY_WORKSHOP],
    IN_PROGRESS: [BOOKING_STATUS.COMPLETED, BOOKING_STATUS.DISPUTED],
    COMPLETED: [BOOKING_STATUS.DISPUTED],
    DISPUTED: [BOOKING_STATUS.COMPLETED]
};

function canTransition(from, to) {
    return Boolean(allowedTransitions[from] && allowedTransitions[from].includes(to));
}

module.exports = {
    BOOKING_STATUS,
    BOOKING_MODE,
    allowedTransitions,
    canTransition
};
